name: FixYoGrammar
description: Corrects the grammatical errors in chat messages post- or pre-send.
authors: [ TehBrian ]
website: https://tehbrian.xyz

version: ${version}
main: xyz.tehbrian.fixyogrammar.FixYoGrammar
api-version: 1.17
