name: FixYoGrammar
description: ${description}
authors: [ TehBrian ]
website: https://github.com/TehBrian/FixYoGrammar

version: ${version}
main: xyz.tehbrian.fixyogrammar.FixYoGrammar
api-version: 1.18
